const {chromium}=require('playwright');const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),base=path.join(__dirname,'test-results/front-production-audit'),report={checks:[],docs:{errors:[],requests:[]}};
const env=Object.fromEntries(fs.readFileSync(path.join(root,'.env'),'utf8').split(/\r?\n/).filter(x=>x&&!x.startsWith('#')&&x.includes('=')).map(x=>{const i=x.indexOf('=');return[x.slice(0,i),x.slice(i+1).replace(/^['"]|['"]$/g,'')]}));
(async()=>{const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
await p.goto('http://localhost:8080');await p.fill('#login-email',env.ADMIN_EMAIL);await p.fill('#login-password',env.ADMIN_PASSWORD);await p.click('#btn-login-submit');await p.locator('#home-providers-table').waitFor();
await p.locator('[data-group="system"] > button').click();await p.locator('nav a[href="#/health"]').click();await p.locator('#health-json').waitFor();await p.waitForFunction(()=>document.querySelector('#health-json').innerText.includes('"status"'));await p.click('#btn-copy-health');const copied=JSON.parse(await p.evaluate(()=>navigator.clipboard.readText()));assert(copied.status);report.checks.push({name:'health: copiar diagnóstico',pass:true,evidence:'JSON válido copiado; CRLF do clipboard Windows normalizado via JSON.parse'});
await p.locator('[data-group="generation"] > button').click();await p.locator('nav a[href="#/workflow-manager"]').click();await p.locator('#wf-import').waitFor();const tag=JSON.parse(fs.readFileSync(path.join(base,'extra/report.json'),'utf8')).tag;const row=p.locator('tr').filter({has:p.getByRole('cell',{name:tag,exact:true})});await row.locator('[data-export]').waitFor();const wait=p.waitForEvent('download');await row.locator('[data-export]').click();const d=await wait;const stream=await d.createReadStream();let chunks=[];for await(const chunk of stream)chunks.push(chunk);const graph=JSON.parse(Buffer.concat(chunks).toString());assert(graph['1']);report.checks.push({name:'workflow: desativar, ativar e exportar JSON',pass:true,evidence:'Exportação por clique validada pelo stream do download; erro EPERM anterior era do filesystem local.'});
const doc=await b.newPage();doc.on('pageerror',e=>report.docs.errors.push(e.message));doc.on('console',m=>{if(m.type()==='error')report.docs.errors.push(m.text())});doc.on('response',r=>report.docs.requests.push({url:r.url(),status:r.status(),type:r.headers()['content-type']}));doc.on('requestfailed',r=>report.docs.requests.push({url:r.url(),failure:r.failure()?.errorText}));await doc.goto('http://localhost:8080/docs/');await doc.waitForTimeout(2500);report.docs.text=await doc.locator('body').innerText();report.docs.html=(await doc.locator('body').innerHTML()).slice(0,2000);report.docs.url=doc.url();await doc.screenshot({path:path.join(base,'swagger.png')});report.checks.push({name:'documentação: link Swagger abre interface',pass:await doc.locator('.swagger-ui').first().isVisible(),evidence:report.docs.errors});
await b.close();fs.writeFileSync(path.join(base,'rechecks.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));})().catch(e=>{console.error(e);process.exitCode=1});
